# Site settings
title:  U.S. Forest Service Web Design Standards Documentation
description: Design and build fast, accessible, mobile-friendly government websites backed by user research.
google_analytics_ua: UA-48605964-43
components_url: 'https://components.designsystem.digital.gov'

# this is for pages that don't have a permalink (primarily posts)
permalink: /whats-new/updates/:year/:month/:day/:title/

# this ensure that posts with future dates are published
future: true

encoding: utf-8

incremental_regeneration_fixer:
  interdependent_files:
    - "_components/colors/*"
    - "_components/form-controls/*"
    - "_components/form-templates/*"
    - "_components/typography/*"

jekyll_get:
  - data: releases
    json: 'https://api.github.com/repos/18F/web-design-standards/releases'
  - data: contributing
    json: 'https://api.github.com/repos/18F/web-design-standards/contents/CONTRIBUTING.md'
    decode_content: true
  - data: standards-sites
    json: 'https://api.github.com/repos/18F/web-design-standards/contents/WHO_IS_USING_USWDS.md'
    decode_content: true

repos:
- name: U.S. Forest Service Web Design Standards
  description: Main repository for the U.S. Forest Service Web Design Standards package
  url: https://github.com/18F/fs-fork-uswds
- name: U.S. Forest Service Web Design Standards Documentation
  description: Documentation for the  U.S. Forest Service Web Design Standards
  url: https://github.com/18F/fs-fork-uswds-site
- name:  U.S. Forest Service Web Design Standards Assets
  description:  U.S. Forest Service Web Design Standards visual design assets
  url: https://github.com/uswds/uswds-assets

sass:
  load_paths:
    - css
    - assets/css

collections:
  components:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ''
      type: components
    values:
      layout: component
  - scope:
      path: ''
      type: posts
    values:
      layout: post

# Build settings
markdown: RedcarpetExtender
redcarpet:
  extensions:
    - smart
    - tables
    - with_toc_data # automatic heading ids

gems:
  - jekyll-redirect-from

exclude:
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
